# === 全局参数 ===
thresholds:
  OUTPUT_CSV: "data/results.csv"                  # 数据保存地址
  ev_spread_min: 0.05                             # 套利触发阈值（例如 5%）
  check_interval_sec: 120                         # 刷新间隔（秒）
  INVESTMENTS: [1000, 5000, 10000, 20000, 50000]  # 起始资金
  MARGIN_USD: 1000                                # 保证金

events:
  - name: "BTC > 100k"
    asset: "BTC"
    polymarket:
      event_title: "Bitcoin above ___ on November 7?"
      market_title: "100,000"

    deribit:
      k1_strike: 99000
      k2_strike: 101000

  - name: "BTC > 102k"
    asset: "BTC"
    polymarket:
      event_title: "Bitcoin above ___ on November 7?"
      market_title: "102,000"

    deribit:
      k1_strike: 101000
      k2_strike: 103000

  - name: "BTC > 104k"
    asset: "BTC"
    polymarket:
      event_title: "Bitcoin above ___ on November 7?"
      market_title: "104,000"

    deribit:
      k1_strike: 103000
      k2_strike: 105000

  - name: "BTC > 106k"
    asset: "BTC"
    polymarket:
      event_title: "Bitcoin above ___ on November 7?"
      market_title: "106,000"

    deribit:
      k1_strike: 105000
      k2_strike: 107000

  - name: "BTC > 108k"
    asset: "BTC"
    polymarket:
      event_title: "Bitcoin above ___ on November 7?"
      market_title: "108,000"

    deribit:
      k1_strike: 107000
      k2_strike: 109000

  - name: "BTC > 110k"
    asset: "BTC"
    polymarket:
      event_title: "Bitcoin above ___ on November 7?"
      market_title: "110,000"

    deribit:
      k1_strike: 109000
      k2_strike: 111000

  - name: "BTC > 112k"
    asset: "BTC"
    polymarket:
      event_title: "Bitcoin above ___ on November 7?"
      market_title: "112,000"

    deribit:
      k1_strike: 111000
      k2_strike: 113000

  - name: "BTC > 114k"
    asset: "BTC"
    polymarket:
      event_title: "Bitcoin above ___ on November 7?"
      market_title: "114,000"

    deribit:
      k1_strike: 113000
      k2_strike: 115000

  - name: "BTC > 116k"
    asset: "BTC"
    polymarket:
      event_title: "Bitcoin above ___ on November 7?"
      market_title: "116,000"

    deribit:
      k1_strike: 115000
      k2_strike: 117000
      
  - name: "BTC > 118k"
    asset: "BTC"
    polymarket:
      event_title: "Bitcoin above ___ on November 7?"
      market_title: "118,000"

    deribit:
      k1_strike: 117000
      k2_strike: 119000

  - name: "Ethereum > 3300"
    asset: "ETH"
    polymarket:
      event_title: "Ethereum above ___ on November 7?"
      market_title: "3,300"

    deribit:
      k1_strike: 3275
      k2_strike: 3300
  
  - name: "Ethereum > 3400"
    asset: "ETH"
    polymarket:
      event_title: "Ethereum above ___ on November 7?"
      market_title: "3,400"

    deribit:
      k1_strike: 3375
      k2_strike: 3400