# === 全局参数 ===
thresholds:
  OUTPUT_CSV: "data/results.csv"                  # 数据保存地址
  ev_spread_min: 0.05                             # 套利触发阈值（例如 5%）
  check_interval_sec: 120                         # 刷新间隔（秒）
  INVESTMENTS: [1000, 5000, 10000, 20000, 50000]  # 起始资金
  MARGIN_USD: 1000                                # 保证金

events:
  - name: "BTC > 108k"
    asset: "BTC"
    polymarket:
      event_title: "Bitcoin above ___ on November 3?"
      market_title: "108,000"

    deribit:
      k1_strike: 107000
      k2_strike: 109000

  - name: "BTC > 110k"
    asset: "BTC"
    polymarket:
      event_title: "Bitcoin above ___ on November 3?"
      market_title: "110,000"

    deribit:
      k1_strike: 109000
      k2_strike: 111000

  - name: "BTC > 112k"
    asset: "BTC"
    polymarket:
      event_title: "Bitcoin above ___ on November 3?"
      market_title: "112,000"

    deribit:
      k1_strike: 111000
      k2_strike: 113000

  - name: "BTC > 114k"
    asset: "BTC"
    polymarket:
      event_title: "Bitcoin above ___ on November 3?"
      market_title: "114,000"

    deribit:
      k1_strike: 113000
      k2_strike: 115000

  - name: "BTC > 116k"
    asset: "BTC"
    polymarket:
      event_title: "Bitcoin above ___ on November 3?"
      market_title: "116,000"

    deribit:
      k1_strike: 115000
      k2_strike: 117000
      
  - name: "BTC > 118k"
    asset: "BTC"
    polymarket:
      event_title: "Bitcoin above ___ on November 3?"
      market_title: "118,000"

    deribit:
      k1_strike: 117000
      k2_strike: 119000

  - name: "Ethereum > 3800"
    asset: "ETH"
    polymarket:
      event_title: "Ethereum above ___ on November 3?"
      market_title: "3,800"

    deribit:
      k1_strike: 3775
      k2_strike: 3800
  
  - name: "Ethereum > 3900"
    asset: "ETH"
    polymarket:
      event_title: "Ethereum above ___ on November 3?"
      market_title: "3,900"

    deribit:
      k1_strike: 3875
      k2_strike: 3925